<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="BMOHANTY02" failures="3" tests="22" name="Test" time="8.274" errors="0" timestamp="2024-01-12T12:20:45 IST">
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.124">
    <failure type="java.lang.AssertionError" message="Test failed: java.lang.AssertionError: Test failed: ORA-00933: SQL command not properly ended
">
      <![CDATA[java.lang.AssertionError: Test failed: java.lang.AssertionError: Test failed: ORA-00933: SQL command not properly ended

at testCases.DataCompletenessValidation.dataCompleteness(DataCompletenessValidation.java:146)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
Caused by: java.util.concurrent.ExecutionException: java.lang.AssertionError: Test failed: ORA-00933: SQL command not properly ended

at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
at testCases.DataCompletenessValidation.dataCompleteness(DataCompletenessValidation.java:138)
... 32 more
Caused by: java.lang.AssertionError: Test failed: ORA-00933: SQL command not properly ended

at databaseFunction.sqlFunction.executeQuery(sqlFunction.java:76)
at testCases.DataCompletenessValidation.lambda$0(DataCompletenessValidation.java:79)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended

at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:702)
at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:608)
at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1248)
at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:1041)
at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:443)
at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:518)
at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:156)
at oracle.jdbc.driver.T4CStatement.executeForDescribe(T4CStatement.java:963)
at oracle.jdbc.driver.OracleStatement.prepareDefineBufferAndExecute(OracleStatement.java:1205)
at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1135)
at oracle.jdbc.driver.OracleStatement.executeSQLSelect(OracleStatement.java:1472)
at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1343)
at oracle.jdbc.driver.OracleStatement.executeQuery(OracleStatement.java:1727)
at oracle.jdbc.driver.OracleStatementWrapper.executeQuery(OracleStatementWrapper.java:380)
at databaseFunction.sqlFunction.executeQuery(sqlFunction.java:46)
... 5 more
Caused by: Error : 933, Position : 42, SQL = select ItemId, ItemName  from items  orde by itemid
, Original SQL = select ItemId, ItemName  from items  orde by itemid
, Error Message = ORA-00933: SQL command not properly ended

at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:710)
... 19 more
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- dataCompleteness -->
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.252"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="4.794"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.1"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.031"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.295"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.014"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.009"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.007"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.007"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.006"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.008"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.009"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.011"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.008"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.012"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.021">
    <failure type="java.lang.AssertionError" message="Test failed: java.lang.AssertionError: Details of Differences:
Row 1:
   Column 2: List1 = EMP_NAME: Sunil, List2 = EMP_NAME: Smith
 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Test failed: java.lang.AssertionError: Details of Differences:
Row 1:
   Column 2: List1 = EMP_NAME: Sunil, List2 = EMP_NAME: Smith
 expected [true] but found [false]
at testCases.DataCompletenessValidation.dataCompleteness(DataCompletenessValidation.java:146)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
Caused by: java.util.concurrent.ExecutionException: java.lang.AssertionError: Details of Differences:
Row 1:
   Column 2: List1 = EMP_NAME: Sunil, List2 = EMP_NAME: Smith
 expected [true] but found [false]
at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
at testCases.DataCompletenessValidation.dataCompleteness(DataCompletenessValidation.java:138)
... 31 more
Caused by: java.lang.AssertionError: Details of Differences:
Row 1:
   Column 2: List1 = EMP_NAME: Sunil, List2 = EMP_NAME: Smith
 expected [true] but found [false]
at testCases.DataCompletenessValidation.lambda$0(DataCompletenessValidation.java:126)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- dataCompleteness -->
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.007"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.005"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.004"/>
  <testcase classname="testCases.TableMetadataValidation" name="tableMetadataValidation" time="0.014">
    <failure type="java.lang.AssertionError" message="Test failed: [{COLUMN_NAME=EMP_ID345, TARGET_COLUMN_NAME=EMP_ID}, {COLUMN_NAME=T_EMP_ID1212, TARGET_COLUMN_NAME=T_EMP_ID}] expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Test failed: [{COLUMN_NAME=EMP_ID345, TARGET_COLUMN_NAME=EMP_ID}, {COLUMN_NAME=T_EMP_ID1212, TARGET_COLUMN_NAME=T_EMP_ID}] expected [true] but found [false]
at testCases.TableMetadataValidation.tableMetadataValidation(TableMetadataValidation.java:62)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
Caused by: java.lang.AssertionError: [{COLUMN_NAME=EMP_ID345, TARGET_COLUMN_NAME=EMP_ID}, {COLUMN_NAME=T_EMP_ID1212, TARGET_COLUMN_NAME=T_EMP_ID}] expected [true] but found [false]
at testCases.TableMetadataValidation.tableMetadataValidation(TableMetadataValidation.java:58)
... 32 more
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- tableMetadataValidation -->
  <testcase classname="testCases.TableMetadataValidation" name="tableMetadataValidation" time="0.005"/>
  <testcase classname="base.TestBase" name="@BeforeSuite setUpBeforeSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setUpBeforeSuite -->
  <testcase classname="base.TestBase" name="@AfterSuite printTestResults" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite printTestResults -->
</testsuite> <!-- Test -->
