<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="BMOHANTY02" failures="1" tests="14" name="testCases.DataCompletenessValidation" time="9.960" errors="0" timestamp="2023-12-29T14:01:54 IST" skipped="0">
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.088"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="5.545"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.008"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.011"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.049">
    <failure message="Test failed: java.lang.AssertionError: Details of Differences:
Row 1:
   Column 2: List1 = EMP_NAME: Sunil, List2 = EMP_NAME: Smith
 expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: java.lang.AssertionError: Details of Differences:
Row 1:
   Column 2: List1 = EMP_NAME: Sunil, List2 = EMP_NAME: Smith
 expected [true] but found [false]
at testCases.DataCompletenessValidation.dataCompleteness(DataCompletenessValidation.java:131)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
Caused by: java.util.concurrent.ExecutionException: java.lang.AssertionError: Details of Differences:
Row 1:
   Column 2: List1 = EMP_NAME: Sunil, List2 = EMP_NAME: Smith
 expected [true] but found [false]
at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
at testCases.DataCompletenessValidation.dataCompleteness(DataCompletenessValidation.java:128)
... 32 more
Caused by: java.lang.AssertionError: Details of Differences:
Row 1:
   Column 2: List1 = EMP_NAME: Sunil, List2 = EMP_NAME: Smith
 expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at testCases.DataCompletenessValidation.lambda$dataCompleteness$2(DataCompletenessValidation.java:101)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- dataCompleteness -->
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.043"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.012"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.014"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.015"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.010"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="4.055"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.011"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.012"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.087"/>
</testsuite> <!-- testCases.DataCompletenessValidation -->
